### ISSUE TITLE
Kopiowanie linku Ptoszek.pl do schowka

### ISSUE THREAD

**Issue by Szibaszyn** [jaczup/ptoszek.pl#12]
Można by dodać:
`navigator.clipboard.writeText("https://ptoszek.pl/")`

**Comment by 9fm** [comment]
nie lepiej zapchać jakimis nwm 2 tysiacami znakow czy cos takiego xd

**Comment by jaczup** [comment]
Myślę, że druga propozycja lepsza, dajcie jakieś skrypty, to dorzucę do index.js :)

**Comment by 9fm** [comment]
Pull request #13

**Comment by 9fm** [comment]
halo mister jaczup

**Comment by jaczup** [comment]
Dodane
